add-itemRequest
Elena2208/java-shareit pull request #4
Opened 2023-02-21 18:21 UTC by Elena2208

2023-02-24 15:50 UTC, Frilock requested changes
В целом критики нет, но не ясно, что за репозиторий в тестах появился. Уберите его

2023-02-24 15:50 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@Transactional
Зачем transactional над классом вешаете? Разве Вам в Ваших тестах нужна транзакция?

2023-02-24 15:50 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Модификаторы пропустили

2023-02-24 15:50 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User,Long> {
А что за репозиторий в тестах появился? Его там не должно быть по идее

2023-02-25 19:39 UTC, Elena2208 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@Transactional
Убираю аннотацию и тесты не проходят

2023-02-26 08:36 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@Transactional
Елена, так надо разобраться почему не проходят =) Скорее всего вы данные не очищаете после тестов. Ну то есть если вы в 1м тесте создали запись, потом в другом у Вас уже есть одна запись. В методе с beforeEach надо очищать данные

2023-02-26 08:36 UTC, Frilock approved these changes
Работу принял, но посмотрите комментарий к тестам.

2023-02-27 20:13 UTC, merged